services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - shared-data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5

  faker:
    build: ./faker
    volumes:
      - shared-data:/db
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    volumes:
      - shared-data:/db
    env_file: .env
    depends_on:
      faker:
        condition: service_completed_successfully

  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "127.0.0.1:8501:8501"
    depends_on:
      backend:
        condition: service_started

volumes:
  shared-data:
